language: bash

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_script:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
    - stack install 
    - stack build
    - bash ./run_tests.sh
